package com.dbsoft.whjd.model;
// Generated 2018-2-12 14:13:31 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * RestoreLugDownMethodResult generated by hbm2java
 */
@Entity
@Table(name = "LugDownMethodBackup", schema = "dbo", catalog = "whjd")
public class LugDownMethodBackup implements java.io.Serializable {

	private int id;
	private String jcbgbh;
	private Float velmaxhp;
	private Float velmaxhpzs;
	private Float maxPower;
	private Float maxPowerLimit;
	private String zdlbglpdjg;
	private Float smokeKlimit;
	private String ydpdjg;
	private Float k100;
	private Float k90;
	private Float k80;
	private Float fdjzsxz;
	private String fdjzspd;
	private Float yw;

	public LugDownMethodBackup() {
	}

	public LugDownMethodBackup(int id, String jcbgbh, Float velmaxhp, Float velmaxhpzs, Float maxPower,
			Float maxPowerLimit, String zdlbglpdjg, Float smokeKlimit, String ydpdjg, Float k100, Float k90,
			Float k80, Float yw) {
		this.id = id;
		this.jcbgbh = jcbgbh;
		this.velmaxhp = velmaxhp;
		this.velmaxhpzs = velmaxhpzs;
		this.maxPower = maxPower;
		this.maxPowerLimit = maxPowerLimit;
		this.zdlbglpdjg = zdlbglpdjg;
		this.smokeKlimit = smokeKlimit;
		this.ydpdjg = ydpdjg;
		this.k100 = k100;
		this.k90 = k90;
		this.k80 = k80;
		this.yw = yw;
	}

	public LugDownMethodBackup(int id, String jcbgbh, Float velmaxhp, Float velmaxhpzs, Float maxPower,
			Float maxPowerLimit, String zdlbglpdjg, Float smokeKlimit, String ydpdjg, Float k100, Float k90,
			Float k80, Float fdjzsxz, String fdjzspd, Float yw) {
		this.id = id;
		this.jcbgbh = jcbgbh;
		this.velmaxhp = velmaxhp;
		this.velmaxhpzs = velmaxhpzs;
		this.maxPower = maxPower;
		this.maxPowerLimit = maxPowerLimit;
		this.zdlbglpdjg = zdlbglpdjg;
		this.smokeKlimit = smokeKlimit;
		this.ydpdjg = ydpdjg;
		this.k100 = k100;
		this.k90 = k90;
		this.k80 = k80;
		this.fdjzsxz = fdjzsxz;
		this.fdjzspd = fdjzspd;
		this.yw = yw;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "JCBGBH", nullable = false, length = 21)
	public String getJcbgbh() {
		return this.jcbgbh;
	}

	public void setJcbgbh(String jcbgbh) {
		this.jcbgbh = jcbgbh;
	}

	@Column(name = "VELMAXHP", nullable = false, precision = 24, scale = 0)
	public Float getVelmaxhp() {
		return this.velmaxhp;
	}

	public void setVelmaxhp(Float velmaxhp) {
		this.velmaxhp = velmaxhp;
	}

	@Column(name = "VELMAXHPZS", nullable = false, precision = 24, scale = 0)
	public Float getVelmaxhpzs() {
		return this.velmaxhpzs;
	}

	public void setVelmaxhpzs(Float velmaxhpzs) {
		this.velmaxhpzs = velmaxhpzs;
	}

	@Column(name = "MaxPower", nullable = false, precision = 24, scale = 0)
	public Float getMaxPower() {
		return this.maxPower;
	}

	public void setMaxPower(Float maxPower) {
		this.maxPower = maxPower;
	}

	@Column(name = "MaxPowerLimit", nullable = false, precision = 24, scale = 0)
	public Float getMaxPowerLimit() {
		return this.maxPowerLimit;
	}

	public void setMaxPowerLimit(Float maxPowerLimit) {
		this.maxPowerLimit = maxPowerLimit;
	}

	@Column(name = "ZDLBGLPDJG", nullable = false, length = 1)
	public String getZdlbglpdjg() {
		return this.zdlbglpdjg;
	}

	public void setZdlbglpdjg(String zdlbglpdjg) {
		this.zdlbglpdjg = zdlbglpdjg;
	}

	@Column(name = "SmokeKLimit", nullable = false, precision = 24, scale = 0)
	public Float getSmokeKlimit() {
		return this.smokeKlimit;
	}

	public void setSmokeKlimit(Float smokeKlimit) {
		this.smokeKlimit = smokeKlimit;
	}

	@Column(name = "YDPDJG", nullable = false, length = 1)
	public String getYdpdjg() {
		return this.ydpdjg;
	}

	public void setYdpdjg(String ydpdjg) {
		this.ydpdjg = ydpdjg;
	}

	@Column(name = "K100", nullable = false, precision = 24, scale = 0)
	public Float getK100() {
		return this.k100;
	}

	public void setK100(Float k100) {
		this.k100 = k100;
	}

	@Column(name = "K90", nullable = false, precision = 24, scale = 0)
	public Float getK90() {
		return this.k90;
	}

	public void setK90(Float k90) {
		this.k90 = k90;
	}

	@Column(name = "K80", nullable = false, precision = 24, scale = 0)
	public Float getK80() {
		return this.k80;
	}

	public void setK80(Float k80) {
		this.k80 = k80;
	}

	@Column(name = "FDJZSXZ", precision = 24, scale = 0)
	public Float getFdjzsxz() {
		return this.fdjzsxz;
	}

	public void setFdjzsxz(Float fdjzsxz) {
		this.fdjzsxz = fdjzsxz;
	}

	@Column(name = "FDJZSPD", length = 2)
	public String getFdjzspd() {
		return this.fdjzspd;
	}

	public void setFdjzspd(String fdjzspd) {
		this.fdjzspd = fdjzspd;
	}

	@Column(name = "YW", nullable = false, precision = 24, scale = 0)
	public Float getYw() {
		return this.yw;
	}

	public void setYw(Float yw) {
		this.yw = yw;
	}

}
