package com.dbsoft.whjd.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * RestoreVehicleInfo generated by hbm2java
 */
@Entity
@Table(name = "RestoreVehicleInfoBackup", schema = "dbo", catalog = "whjd")
public class RestoreVehicleInfoBackup implements java.io.Serializable {

	private int id;
	private String vehicle;
	private String cphm;
	private String cllx;
	private String czmc;
	private String lxdz;
	private String lxdh;
	private String cpmc;
	private String clxh;
	private String syxz;
	private String clsbm;
	private Float zdzzl;
	private Float jzzl;
	private Date ccrq;
	private Date fzrq;
	private Date ccdjrq;
	private String fdjxh;
	private String fdjh;
	private Float ljxslc;
	private String jcff;
	private String pfbz;
	private String qdfs;
	private Float qdltqy;
	private Float fdjpl;

	public RestoreVehicleInfoBackup() {
	}

	public RestoreVehicleInfoBackup(int id, String vehicle, String cphm, String cllx, String czmc, String cpmc, String clxh,
			String syxz, String clsbm, Float zdzzl, Date ccrq, Date ccdjrq, String fdjh) {
		this.id = id;
		this.vehicle = vehicle;
		this.cphm = cphm;
		this.cllx = cllx;
		this.czmc = czmc;
		this.cpmc = cpmc;
		this.clxh = clxh;
		this.syxz = syxz;
		this.clsbm = clsbm;
		this.zdzzl = zdzzl;
		this.ccrq = ccrq;
		this.ccdjrq = ccdjrq;
		this.fdjh = fdjh;
	}

	public RestoreVehicleInfoBackup(int id, String vehicle, String cphm, String cllx, String czmc, String lxdz, String lxdh,
			String cpmc, String clxh, String syxz, String clsbm, Float zdzzl, Float jzzl, Date ccrq, Date fzrq,
			Date ccdjrq, String fdjxh, String fdjh, Float ljxslc, String jcff, String pfbz, String qdfs, Float qdltqy,
			Float fdjpl) {
		this.id = id;
		this.vehicle = vehicle;
		this.cphm = cphm;
		this.cllx = cllx;
		this.czmc = czmc;
		this.lxdz = lxdz;
		this.lxdh = lxdh;
		this.cpmc = cpmc;
		this.clxh = clxh;
		this.syxz = syxz;
		this.clsbm = clsbm;
		this.zdzzl = zdzzl;
		this.jzzl = jzzl;
		this.ccrq = ccrq;
		this.fzrq = fzrq;
		this.ccdjrq = ccdjrq;
		this.fdjxh = fdjxh;
		this.fdjh = fdjh;
		this.ljxslc = ljxslc;
		this.jcff = jcff;
		this.pfbz = pfbz;
		this.qdfs = qdfs;
		this.qdltqy = qdltqy;
		this.fdjpl = fdjpl;
	}

	
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Vehicle", nullable = false, length = 32)
	public String getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(String vehicle) {
		this.vehicle = vehicle;
	}

	@Column(name = "CPHM", nullable = false, length = 10)
	public String getCphm() {
		return this.cphm;
	}

	public void setCphm(String cphm) {
		this.cphm = cphm;
	}

	@Column(name = "CLLX", nullable = false, length = 3)
	public String getCllx() {
		return this.cllx;
	}

	public void setCllx(String cllx) {
		this.cllx = cllx;
	}

	@Column(name = "CZMC", nullable = false, length = 50)
	public String getCzmc() {
		return this.czmc;
	}

	public void setCzmc(String czmc) {
		this.czmc = czmc;
	}

	@Column(name = "LXDZ", length = 150)
	public String getLxdz() {
		return this.lxdz;
	}

	public void setLxdz(String lxdz) {
		this.lxdz = lxdz;
	}

	@Column(name = "LXDH", length = 20)
	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	@Column(name = "CPMC", nullable = false, length = 20)
	public String getCpmc() {
		return this.cpmc;
	}

	public void setCpmc(String cpmc) {
		this.cpmc = cpmc;
	}

	@Column(name = "CLXH", nullable = false, length = 20)
	public String getClxh() {
		return this.clxh;
	}

	public void setClxh(String clxh) {
		this.clxh = clxh;
	}

	@Column(name = "SYXZ", nullable = false, length = 1)
	public String getSyxz() {
		return this.syxz;
	}

	public void setSyxz(String syxz) {
		this.syxz = syxz;
	}

	@Column(name = "CLSBM", nullable = false, length = 20)
	public String getClsbm() {
		return this.clsbm;
	}

	public void setClsbm(String clsbm) {
		this.clsbm = clsbm;
	}

	@Column(name = "ZDZZL", nullable = false, precision = 24, scale = 0)
	public Float getZdzzl() {
		return this.zdzzl;
	}

	public void setZdzzl(Float zdzzl) {
		this.zdzzl = zdzzl;
	}

	@Column(name = "JZZL", precision = 24, scale = 0)
	public Float getJzzl() {
		return this.jzzl;
	}

	public void setJzzl(Float jzzl) {
		this.jzzl = jzzl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CCRQ", nullable = false, length = 10)
	public Date getCcrq() {
		return this.ccrq;
	}

	public void setCcrq(Date ccrq) {
		this.ccrq = ccrq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FZRQ", length = 10)
	public Date getFzrq() {
		return this.fzrq;
	}

	public void setFzrq(Date fzrq) {
		this.fzrq = fzrq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CCDJRQ", nullable = false, length = 10)
	public Date getCcdjrq() {
		return this.ccdjrq;
	}

	public void setCcdjrq(Date ccdjrq) {
		this.ccdjrq = ccdjrq;
	}

	@Column(name = "FDJXH", length = 20)
	public String getFdjxh() {
		return this.fdjxh;
	}

	public void setFdjxh(String fdjxh) {
		this.fdjxh = fdjxh;
	}

	@Column(name = "FDJH", nullable = false, length = 20)
	public String getFdjh() {
		return this.fdjh;
	}

	public void setFdjh(String fdjh) {
		this.fdjh = fdjh;
	}

	@Column(name = "LJXSLC", precision =24, scale = 0)
	public Float getLjxslc() {
		return this.ljxslc;
	}

	public void setLjxslc(Float ljxslc) {
		this.ljxslc = ljxslc;
	}

	@Column(name = "JCFF", length = 1)
	public String getJcff() {
		return this.jcff;
	}

	public void setJcff(String jcff) {
		this.jcff = jcff;
	}

	@Column(name = "PFBZ", length = 1)
	public String getPfbz() {
		return this.pfbz;
	}

	public void setPfbz(String pfbz) {
		this.pfbz = pfbz;
	}

	@Column(name = "QDFS", length = 40)
	public String getQdfs() {
		return this.qdfs;
	}

	public void setQdfs(String qdfs) {
		this.qdfs = qdfs;
	}

	@Column(name = "QDLTQY", precision = 24, scale = 0)
	public Float getQdltqy() {
		return this.qdltqy;
	}

	public void setQdltqy(Float qdltqy) {
		this.qdltqy = qdltqy;
	}

	@Column(name = "FDJPL", precision = 24, scale = 0)
	public Float getFdjpl() {
		return this.fdjpl;
	}

	public void setFdjpl(Float fdjpl) {
		this.fdjpl = fdjpl;
	}

}
