package com.dbsoft.whjd.model;
// Generated 2018-2-12 14:13:31 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * RestoreDectectionBase generated by hbm2java
 */
@Entity
@Table(name = "RestoreDectectionBaseBackup", schema = "dbo", catalog = "whjd")
public class RestoreDectectionBaseBackup implements java.io.Serializable {

	private int id;
	private String testNo;
	private String jczbh;
	private String jczmc;
	private String wtzsbh;
	private Date jcrq;
	private String jclry;
	private String jcczy;
	private String jcjsy;
	private String clsbdh;
	private String cphm;
	private String vehicleType;
	private String cllx;
	private Date ccrq;
	private String yyxz;
	private String czmc;
	private Date ccdjrq;
	private String rlzl;
	private String testType;
	private String pfbz;
	private String hbflbz;
	private int jccs;
	private Float wd;
	private Float sd;
	private Float dqy;
	private String pdjg;
	private String jclxbh;

	public RestoreDectectionBaseBackup() {
	}

	public RestoreDectectionBaseBackup(int id, String testNo, String jczbh, String wtzsbh, Date jcrq, String jclry,
			String jcczy, String jcjsy, String clsbdh, String cphm, String vehicleType, String cllx, Date ccrq,
			String yyxz, String czmc, Date ccdjrq, String rlzl, String testType, String pfbz, String hbflbz, int jccs,
			String pdjg, String jclxbh) {
		this.id = id;
		this.testNo = testNo;
		this.jczbh = jczbh;
		this.wtzsbh = wtzsbh;
		this.jcrq = jcrq;
		this.jclry = jclry;
		this.jcczy = jcczy;
		this.jcjsy = jcjsy;
		this.clsbdh = clsbdh;
		this.cphm = cphm;
		this.vehicleType = vehicleType;
		this.cllx = cllx;
		this.ccrq = ccrq;
		this.yyxz = yyxz;
		this.czmc = czmc;
		this.ccdjrq = ccdjrq;
		this.rlzl = rlzl;
		this.testType = testType;
		this.pfbz = pfbz;
		this.hbflbz = hbflbz;
		this.jccs = jccs;
		this.pdjg = pdjg;
		this.jclxbh = jclxbh;
	}

	public RestoreDectectionBaseBackup(int id, String testNo, String jczbh, String jczmc, String wtzsbh, Date jcrq,
			String jclry, String jcczy, String jcjsy, String clsbdh, String cphm, String vehicleType, String cllx,
			Date ccrq, String yyxz, String czmc, Date ccdjrq, String rlzl, String testType, String pfbz, String hbflbz,
			int jccs, Float wd, Float sd, Float dqy, String pdjg, String jclxbh) {
		this.id = id;
		this.testNo = testNo;
		this.jczbh = jczbh;
		this.jczmc = jczmc;
		this.wtzsbh = wtzsbh;
		this.jcrq = jcrq;
		this.jclry = jclry;
		this.jcczy = jcczy;
		this.jcjsy = jcjsy;
		this.clsbdh = clsbdh;
		this.cphm = cphm;
		this.vehicleType = vehicleType;
		this.cllx = cllx;
		this.ccrq = ccrq;
		this.yyxz = yyxz;
		this.czmc = czmc;
		this.ccdjrq = ccdjrq;
		this.rlzl = rlzl;
		this.testType = testType;
		this.pfbz = pfbz;
		this.hbflbz = hbflbz;
		this.jccs = jccs;
		this.wd = wd;
		this.sd = sd;
		this.dqy = dqy;
		this.pdjg = pdjg;
		this.jclxbh = jclxbh;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TestNo", nullable = false, length = 21)
	public String getTestNo() {
		return this.testNo;
	}

	public void setTestNo(String testNo) {
		this.testNo = testNo;
	}

	@Column(name = "JCZBH", nullable = false, length = 20)
	public String getJczbh() {
		return this.jczbh;
	}

	public void setJczbh(String jczbh) {
		this.jczbh = jczbh;
	}

	@Column(name = "JCZMC", length = 50)
	public String getJczmc() {
		return this.jczmc;
	}

	public void setJczmc(String jczmc) {
		this.jczmc = jczmc;
	}

	@Column(name = "WTZSBH", nullable = false, length = 20)
	public String getWtzsbh() {
		return this.wtzsbh;
	}

	public void setWtzsbh(String wtzsbh) {
		this.wtzsbh = wtzsbh;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "jcrq", nullable = false, length = 10)
	public Date getJcrq() {
		return this.jcrq;
	}

	public void setJcrq(Date jcrq) {
		this.jcrq = jcrq;
	}

	@Column(name = "JCLRY", nullable = false, length = 20)
	public String getJclry() {
		return this.jclry;
	}

	public void setJclry(String jclry) {
		this.jclry = jclry;
	}

	@Column(name = "JCCZY", nullable = false, length = 20)
	public String getJcczy() {
		return this.jcczy;
	}

	public void setJcczy(String jcczy) {
		this.jcczy = jcczy;
	}

	@Column(name = "JCJSY", nullable = false, length = 20)
	public String getJcjsy() {
		return this.jcjsy;
	}

	public void setJcjsy(String jcjsy) {
		this.jcjsy = jcjsy;
	}

	@Column(name = "CLSBDH", nullable = false, length = 15)
	public String getClsbdh() {
		return this.clsbdh;
	}

	public void setClsbdh(String clsbdh) {
		this.clsbdh = clsbdh;
	}

	@Column(name = "CPHM", nullable = false, length = 10)
	public String getCphm() {
		return this.cphm;
	}

	public void setCphm(String cphm) {
		this.cphm = cphm;
	}

	@Column(name = "VehicleType", nullable = false, length = 5)
	public String getVehicleType() {
		return this.vehicleType;
	}

	public void setVehicleType(String vehicleType) {
		this.vehicleType = vehicleType;
	}

	@Column(name = "CLLX", nullable = false, length = 3)
	public String getCllx() {
		return this.cllx;
	}

	public void setCllx(String cllx) {
		this.cllx = cllx;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CCRQ", nullable = false, length = 10)
	public Date getCcrq() {
		return this.ccrq;
	}

	public void setCcrq(Date ccrq) {
		this.ccrq = ccrq;
	}

	@Column(name = "YYXZ", nullable = false, length = 1)
	public String getYyxz() {
		return this.yyxz;
	}

	public void setYyxz(String yyxz) {
		this.yyxz = yyxz;
	}

	@Column(name = "CZMC", nullable = false, length = 20)
	public String getCzmc() {
		return this.czmc;
	}

	public void setCzmc(String czmc) {
		this.czmc = czmc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CCDJRQ", nullable = false, length = 10)
	public Date getCcdjrq() {
		return this.ccdjrq;
	}

	public void setCcdjrq(Date ccdjrq) {
		this.ccdjrq = ccdjrq;
	}

	@Column(name = "RLZL", nullable = false, length = 1)
	public String getRlzl() {
		return this.rlzl;
	}

	public void setRlzl(String rlzl) {
		this.rlzl = rlzl;
	}

	@Column(name = "TestType", nullable = false, length = 1)
	public String getTestType() {
		return this.testType;
	}

	public void setTestType(String testType) {
		this.testType = testType;
	}

	@Column(name = "PFBZ", nullable = false, length = 1)
	public String getPfbz() {
		return this.pfbz;
	}

	public void setPfbz(String pfbz) {
		this.pfbz = pfbz;
	}

	@Column(name = "HBFLBZ", nullable = false, length = 1)
	public String getHbflbz() {
		return this.hbflbz;
	}

	public void setHbflbz(String hbflbz) {
		this.hbflbz = hbflbz;
	}

	@Column(name = "JCCS", nullable = false)
	public int getJccs() {
		return this.jccs;
	}

	public void setJccs(int jccs) {
		this.jccs = jccs;
	}

	@Column(name = "WD", precision = 24, scale = 0)
	public Float getWd() {
		return this.wd;
	}

	public void setWd(Float wd) {
		this.wd = wd;
	}

	@Column(name = "SD", precision = 24, scale = 0)
	public Float getSd() {
		return this.sd;
	}

	public void setSd(Float sd) {
		this.sd = sd;
	}

	@Column(name = "DQY", precision = 24, scale = 0)
	public Float getDqy() {
		return this.dqy;
	}

	public void setDqy(Float dqy) {
		this.dqy = dqy;
	}

	@Column(name = "pdjg", nullable = false, length = 10)
	public String getPdjg() {
		return this.pdjg;
	}

	public void setPdjg(String pdjg) {
		this.pdjg = pdjg;
	}

	@Column(name = "jclxbh", nullable = false, length = 10)
	public String getJclxbh() {
		return this.jclxbh;
	}

	public void setJclxbh(String jclxbh) {
		this.jclxbh = jclxbh;
	}

}
