package com.dbsoft.whjd.model;
// Generated 2018-2-12 14:13:31 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * RestoreTwoSpeedIdleMethodResult generated by hbm2java
 */
@Entity
@Table(name = "TwoSpeedIdleMethodBackup", schema = "dbo", catalog = "whjd")
public class TwoSpeedIdleMethodBackup implements java.io.Serializable {

	private int id;
	private String jcbgbh;
	private Float lambda;
	private Float lambdaLimit;
	private String lambdaJudge;
	private Float lowIdleColimit;
	private Float lowIdleCo;
	private String lowIdleCojudge;
	private Float lowIdleHclimit;
	private Float lowIdleHc;
	private String lowIdleHcjudge;
	private Float fdjdszs;
	private Float ddsjywd;
	private Float highIdleColimit;
	private Float highIdleCo;
	private String highIdleCojudge;
	private Float highIdleHclimit;
	private Float highIdleHc;
	private String highIdleHcjudge;
	private Float gdszs;
	private Float gdsjywd;

	public TwoSpeedIdleMethodBackup() {
	}

	public TwoSpeedIdleMethodBackup(int id, String jcbgbh, Float lambda, Float lambdaLimit, String lambdaJudge,
			Float lowIdleColimit, Float lowIdleCo, String lowIdleCojudge, Float lowIdleHclimit, Float lowIdleHc,
			String lowIdleHcjudge, Float fdjdszs, Float ddsjywd, Float highIdleColimit, Float highIdleCo,
			String highIdleCojudge, Float highIdleHclimit, Float highIdleHc, String highIdleHcjudge, Float gdszs,
			Float gdsjywd) {
		this.id = id;
		this.jcbgbh = jcbgbh;
		this.lambda = lambda;
		this.lambdaLimit = lambdaLimit;
		this.lambdaJudge = lambdaJudge;
		this.lowIdleColimit = lowIdleColimit;
		this.lowIdleCo = lowIdleCo;
		this.lowIdleCojudge = lowIdleCojudge;
		this.lowIdleHclimit = lowIdleHclimit;
		this.lowIdleHc = lowIdleHc;
		this.lowIdleHcjudge = lowIdleHcjudge;
		this.fdjdszs = fdjdszs;
		this.ddsjywd = ddsjywd;
		this.highIdleColimit = highIdleColimit;
		this.highIdleCo = highIdleCo;
		this.highIdleCojudge = highIdleCojudge;
		this.highIdleHclimit = highIdleHclimit;
		this.highIdleHc = highIdleHc;
		this.highIdleHcjudge = highIdleHcjudge;
		this.gdszs = gdszs;
		this.gdsjywd = gdsjywd;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "JCBGBH", nullable = false, length = 21)
	public String getJcbgbh() {
		return this.jcbgbh;
	}

	public void setJcbgbh(String jcbgbh) {
		this.jcbgbh = jcbgbh;
	}

	@Column(name = "Lambda", nullable = false, precision = 24, scale = 0)
	public Float getLambda() {
		return this.lambda;
	}

	public void setLambda(Float lambda) {
		this.lambda = lambda;
	}

	@Column(name = "LambdaLimit", nullable = false, precision = 24, scale = 0)
	public Float getLambdaLimit() {
		return this.lambdaLimit;
	}

	public void setLambdaLimit(Float lambdaLimit) {
		this.lambdaLimit = lambdaLimit;
	}

	@Column(name = "LambdaJudge", nullable = false, length = 1)
	public String getLambdaJudge() {
		return this.lambdaJudge;
	}

	public void setLambdaJudge(String lambdaJudge) {
		this.lambdaJudge = lambdaJudge;
	}

	@Column(name = "LowIdleCOLimit", nullable = false, precision = 24, scale = 0)
	public Float getLowIdleColimit() {
		return this.lowIdleColimit;
	}

	public void setLowIdleColimit(Float lowIdleColimit) {
		this.lowIdleColimit = lowIdleColimit;
	}

	@Column(name = "LowIdleCO", nullable = false, precision = 24, scale = 0)
	public Float getLowIdleCo() {
		return this.lowIdleCo;
	}

	public void setLowIdleCo(Float lowIdleCo) {
		this.lowIdleCo = lowIdleCo;
	}

	@Column(name = "LowIdleCOJudge", nullable = false, length = 1)
	public String getLowIdleCojudge() {
		return this.lowIdleCojudge;
	}

	public void setLowIdleCojudge(String lowIdleCojudge) {
		this.lowIdleCojudge = lowIdleCojudge;
	}

	@Column(name = "LowIdleHCLimit", nullable = false, precision = 24, scale = 0)
	public Float getLowIdleHclimit() {
		return this.lowIdleHclimit;
	}

	public void setLowIdleHclimit(Float lowIdleHclimit) {
		this.lowIdleHclimit = lowIdleHclimit;
	}

	@Column(name = "LowIdleHC", nullable = false, precision = 24, scale = 0)
	public Float getLowIdleHc() {
		return this.lowIdleHc;
	}

	public void setLowIdleHc(Float lowIdleHc) {
		this.lowIdleHc = lowIdleHc;
	}

	@Column(name = "LowIdleHCJudge", nullable = false, length = 1)
	public String getLowIdleHcjudge() {
		return this.lowIdleHcjudge;
	}

	public void setLowIdleHcjudge(String lowIdleHcjudge) {
		this.lowIdleHcjudge = lowIdleHcjudge;
	}

	@Column(name = "FDJDSZS", nullable = false, precision = 24, scale = 0)
	public Float getFdjdszs() {
		return this.fdjdszs;
	}

	public void setFdjdszs(Float fdjdszs) {
		this.fdjdszs = fdjdszs;
	}

	@Column(name = "DDSJYWD", nullable = false, precision = 24, scale = 0)
	public Float getDdsjywd() {
		return this.ddsjywd;
	}

	public void setDdsjywd(Float ddsjywd) {
		this.ddsjywd = ddsjywd;
	}

	@Column(name = "HighIdleCOLimit", nullable = false, precision = 24, scale = 0)
	public Float getHighIdleColimit() {
		return this.highIdleColimit;
	}

	public void setHighIdleColimit(Float highIdleColimit) {
		this.highIdleColimit = highIdleColimit;
	}

	@Column(name = "HighIdleCO", nullable = false, precision = 24, scale = 0)
	public Float getHighIdleCo() {
		return this.highIdleCo;
	}

	public void setHighIdleCo(Float highIdleCo) {
		this.highIdleCo = highIdleCo;
	}

	@Column(name = "HighIdleCOJudge", nullable = false, length = 1)
	public String getHighIdleCojudge() {
		return this.highIdleCojudge;
	}

	public void setHighIdleCojudge(String highIdleCojudge) {
		this.highIdleCojudge = highIdleCojudge;
	}

	@Column(name = "HighIdleHCLimit", nullable = false, precision = 24, scale = 0)
	public Float getHighIdleHclimit() {
		return this.highIdleHclimit;
	}

	public void setHighIdleHclimit(Float highIdleHclimit) {
		this.highIdleHclimit = highIdleHclimit;
	}

	@Column(name = "HighIdleHC", nullable = false, precision = 24, scale = 0)
	public Float getHighIdleHc() {
		return this.highIdleHc;
	}

	public void setHighIdleHc(Float highIdleHc) {
		this.highIdleHc = highIdleHc;
	}

	@Column(name = "HighIdleHCJudge", nullable = false, length = 1)
	public String getHighIdleHcjudge() {
		return this.highIdleHcjudge;
	}

	public void setHighIdleHcjudge(String highIdleHcjudge) {
		this.highIdleHcjudge = highIdleHcjudge;
	}

	@Column(name = "GDSZS", nullable = false, precision = 24, scale = 0)
	public Float getGdszs() {
		return this.gdszs;
	}

	public void setGdszs(Float gdszs) {
		this.gdszs = gdszs;
	}

	@Column(name = "GDSJYWD", nullable = false, precision = 24, scale = 0)
	public Float getGdsjywd() {
		return this.gdsjywd;
	}

	public void setGdsjywd(Float gdsjywd) {
		this.gdsjywd = gdsjywd;
	}

}
